name: Publish Spylgass Keybind to Modrinth

on:
  workflow_dispatch:
    inputs:
      modrinth:
        default: true
        description: "Publish in modrinth"
        type: boolean
      fabric:
        default: true
        description: "Publish in fabric version"
        type: boolean
      minecraftVersion:
        description: "Minecraft Version. Ex: [1.20.2,1.21)"
        default: "[1.21.9,1.22)"
        required: true
      minecraftBaseVersion:
        description: "Minecraft Base Version. Ex: 1.20.2"
        default: "1.21.9"
        required: true
      javaVersion:
        required: true
        default: 21
        description: "Java Version"
        type: number
      modVersion:
        required: true
        default: "1.0.0"
        description: "Mod version string. Ex: 1.5"
        type: string
      slug:
        required: true
        default: "spyglass-keybind"
        type: string
      releaseName:
        required: true
        default: "Spyglass Keybind"
        description: "Mod publish name. Ex: Spyglass Keybind"
        type: string

env:
  MINECRAFT_VERSION: ${{ inputs.minecraftVersion }}
  MINECRAFT_BASE_VERSION: ${{ inputs.minecraftBaseVersion }}
  JAVA_VERSION: ${{ inputs.javaVersion }}
  VERSION: ${{ inputs.modVersion }}
  RELEASE_NAME: ${{ inputs.releaseName }}
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "${{env.JAVA_VERSION}}"

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish Fabric (Modrinth)
        if: ${{ inputs.modrinth && inputs.fabric }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ inputs.slug }}
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          modrinth-featured: true

          files: fabric/build/libs/!(*-dev-shadow|*-sources).jar

          name: "[Fabric ${{env.MINECRAFT_BASE_VERSION}}] ${{env.RELEASE_NAME}} ${{env.VERSION}}"
          version: "${{env.VERSION}}+mc${{env.MINECRAFT_BASE_VERSION}}+fabric"
          version-type: release
          changelog-file: changelog.md

          loaders: "fabric"
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
